version: '3.2'

services:

  mongodb:
    image: 'mongo'
    environment:
      MONGO_INITDB_ROOT_DATABASE: localapp
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongo
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./mongo-volume:/data/db
    ports:
      - "27117:27017"
    restart: always
    labels:
      - "traefik.enable=false"

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - "mongodb"