version: '3.2'

services:
  app:
    container_name: 'EC-App'
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ENV_NAME: dev
    ports:
      - 7001:7001
    networks:
      - ec-proxy-net

networks:
  ec-proxy-net:
    name: ec_network
