name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.13.1
        uses: actions/setup-node@v1
        with:
          node-version: '12.13.1'
      - name: yarn install
        run: yarn install
      - name: yarn lint
        run: yarn lint
      - name: yarn build
        run: yarn run build
      - name: yarn test
        run: yarn test