name: CI

on:
  push:
    jobs:
      build:
        runs-on: ubuntu-18.04
        steps:
          - uses: actions/checkout@v2
          - name: Use Node.js 14.15.4
            uses: actions/setup-node@v1
            with:
              node-version: '14.15.4'
          - name: npm install
            run: npm install